title: AWAre - Adaptive Assistance
description: An open source assistance platform for research and production!
theme: just-the-docs

url: https://hoestreich.github.io/doc2

aux_links:
  "Docs on github": 
  - https://github.com/hoestreich/doc2
  "Demo instance":
  - https://aware-demo.bob.ci.cit-ec.net
