title: AWAre - Adaptive Assistance
description: An open source assistance platform for research and production!
theme: just-the-docs

url: https://hoestreich.github.io/doc2

aux_links:
  Template Repository: https://github.com/hoestreich/doc2
